# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-volume" do
  name "git-volume"
  desc "Manage environment files across Git worktrees"
  homepage "https://github.com/laggu/git-volume"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-volume"

  on_macos do
    on_intel do
      url "https://github.com/laggu/git-volume/releases/download/v#{version}/git-volume_#{version}_darwin_amd64.tar.gz"
      sha256 "5210b957df199fca8b4e7b5ecbecf71a30331096ba2fe97ce340b7a76e75cd5a"
    end
    on_arm do
      url "https://github.com/laggu/git-volume/releases/download/v#{version}/git-volume_#{version}_darwin_arm64.tar.gz"
      sha256 "21285225ea50717b2e1fc61ef0958cf952b128aec13f7f1a704abc6e7f411431"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/laggu/git-volume/releases/download/v#{version}/git-volume_#{version}_linux_amd64.tar.gz"
      sha256 "7e7bb101e6bc25cc61ae6043f4e395f2c09b7db0b5b3f46b10348e5cf4ca1781"
    end
    on_arm do
      url "https://github.com/laggu/git-volume/releases/download/v#{version}/git-volume_#{version}_linux_arm64.tar.gz"
      sha256 "4a636a062dcbd75d1f865d6c8f5920b88d0a0aa6112c438c1e0646fd8062393b"
    end
  end

  # No zap stanza required
end
