# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-volume" do
  name "git-volume"
  desc "Manage environment files across Git worktrees"
  homepage "https://github.com/laggu/git-volume"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-volume"

  on_macos do
    on_intel do
      url "https://github.com/laggu/git-volume/releases/download/v#{version}/git-volume_#{version}_darwin_amd64.tar.gz"
      sha256 "b97c20a500ce8bc5dbcee01263f13d69ce5e31eb06a1b5b977e27e3bc5466675"
    end
    on_arm do
      url "https://github.com/laggu/git-volume/releases/download/v#{version}/git-volume_#{version}_darwin_arm64.tar.gz"
      sha256 "dce598eb1322da02d09e58f70e778987c3bab042ce51fac698ade4fba592a360"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/laggu/git-volume/releases/download/v#{version}/git-volume_#{version}_linux_amd64.tar.gz"
      sha256 "afcfb8243925f6779bde9b34319fb9bfd47c19ebbb4a6b7c5d90c9ea54e622e5"
    end
    on_arm do
      url "https://github.com/laggu/git-volume/releases/download/v#{version}/git-volume_#{version}_linux_arm64.tar.gz"
      sha256 "a4112dd798628efa22ce012ed14de179a0e2d7dbeff1b7b33f9cb0c426049919"
    end
  end

  # No zap stanza required
end
